# Generated by Django 3.0 on 2021-04-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210402_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_sent',
            new_name='email_send',
        ),
    ]
