# Generated by Django 3.0.5 on 2021-03-16 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='author of recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='choose ingredients for your recipe', through='recipes.RecipeIngredient', to='recipes.Ingredient', verbose_name='ingredient for recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_tag',
            field=models.ManyToManyField(to='recipes.RecipeTag'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('title', 'dimension')},
        ),
    ]
