# Generated by Django 3.0 on 2021-03-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210328_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetag',
            name='color',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
