# Generated by Django 3.0.5 on 2021-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210316_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipes/de111faultImage.png', help_text='Upload a recipe image', null=True, upload_to='recipes/', verbose_name='image for recipe'),
        ),
    ]
