# Generated by Django 3.0.5 on 2021-03-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210313_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipes/defaultImage.png', help_text='Upload a recipe image', null=True, upload_to='recipes/', verbose_name='image for recipe'),
        ),
    ]
