# Generated by Django 3.0 on 2021-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210329_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetag',
            name='tag_russian',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='meal_time',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], max_length=20, unique=True, verbose_name='meal for time'),
        ),
    ]
