# Generated by Django 3.0 on 2021-04-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210417_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetag',
            name='color',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
